export type ModuleStatus = 'api-ready' | 'api-needed' | 'frontend-draft';
export type ModuleKind = 'crud' | 'workflow' | 'analytics' | 'settings';

export interface ModuleColumn {
  label: string;
  key: string;
  type?: 'text' | 'date' | 'money' | 'badge' | 'km' | 'number' | 'image';
}

export interface ModuleFormField {
  label: string;
  name: string;
  type?: 'text' | 'email' | 'number' | 'date' | 'textarea' | 'select' | 'file';
  required?: boolean;
  multiple?: boolean;
  accept?: string;
  optionsEndpoint?: string;
  optionLabel?: string;
  optionFormatter?: (option: any) => string;
  staticOptions?: { value: string; label: string }[];
  defaultValue?: string | number;
  readOnly?: boolean;
  hidden?: boolean;
}

export interface ModuleDefinition {
  title: string;
  description: string;
  endpoint?: string;
  kind?: ModuleKind;
  status: ModuleStatus;
  primaryAction: string;
  fields: string[];
  columns?: ModuleColumn[];
  formFields?: ModuleFormField[];
  detailRoute?: string;
  exportRoute?: string;  // ex: 'facturations' → /facturations/{id}/export
  exportFilename?: (item: any) => string;
  transformOnSubmit?: (data: Record<string, string | number>, context: { isEditing: boolean }) => Record<string, string | number>;
  // Configuration menu
  menu?: {
    label: string;
    icon?: string;
    badge?: number | { endpoint: string; path: string };
  };
  hideFromDynamicMenu?: boolean;
}

// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
// @ts-ignore
export const modules: Record<string, ModuleDefinition> = {
  dashboard: {
    title: 'Tableau de bord',
    description: 'KPIs temps reel, alertes metier et pilotage global du parc automobile.',
    kind: 'analytics',
    status: 'api-ready',
    primaryAction: 'Actualiser les KPIs',
    fields: ['Ventes du mois', 'Chiffre affaires', 'Vehicules disponibles', 'Stock critique'],
    menu: { label: 'Tableau de bord' },
    hideFromDynamicMenu: true,
  },
  voitures: {
    title: 'Vehicules',
    description: 'Gérez l\'ensemble de la flotte — ajout, modification, statuts et suivi de chaque véhicule.',
    endpoint: '/voitures',
    kind: 'crud',
    status: 'api-ready',
      detailRoute: 'voitures',
      primaryAction: 'Ajouter un vehicule',
    fields: ['Marque', 'Modele', 'Annee', 'Prix XOF', 'Statut'],
    columns: [
      { label: 'Marque', key: 'marque' },
      { label: 'Modele', key: 'modele' },
      { label: 'Annee', key: 'annee', type: 'number' as const },
      { label: 'Prix XOF', key: 'prix', type: 'money' as const },
      { label: 'Statut', key: 'statut', type: 'badge' as const },
    ],
    formFields: [
      { label: 'Marque', name: 'marque', required: true },
      { label: 'Modele', name: 'modele', required: true },
      { label: 'Annee', name: 'annee', type: 'number' },
      { label: 'Prix location / jour (XOF)', name: 'prix', type: 'number' },
      { label: 'Prix de vente (XOF)', name: 'prix_vente', type: 'number' },
      { label: 'Numero chassis', name: 'numero_chassis', required: true },
      { label: 'Couleur', name: 'couleur' },
      { label: 'Statut', name: 'statut', type: 'select', required: true, staticOptions: [
        { value: 'disponible', label: 'Disponible' },
        { value: 'vendu', label: 'Vendu' },
        { value: 'loue', label: 'Loué' },
        { value: 'en_maintenance', label: 'En maintenance' },
        { value: 'hors_service', label: 'Hors service' },
        { value: 'reserve', label: 'Réservé' },
      ]},
      { label: 'Fournisseur', name: 'id_fournisseur', type: 'select', optionsEndpoint: '/fournisseurs', optionFormatter: (option) => option?.nom || `Fournisseur #${option?.id}` },
      { label: 'Énergie', name: 'energie', type: 'select', staticOptions: [
        { value: 'essence', label: 'Essence' },
        { value: 'diesel', label: 'Diesel' },
        { value: 'hybride', label: 'Hybride' },
        { value: 'electrique', label: 'Électrique' },
        { value: 'gpl', label: 'GPL' },
      ]},
      { label: 'Kilométrage', name: 'kilometrage', type: 'number' },
      { label: 'État général', name: 'etat', type: 'select', staticOptions: [
        { value: 'neuf', label: 'Neuf' },
        { value: 'occasion', label: 'Occasion' },
        { value: 'reconditionne', label: 'Reconditionné' },
      ]},
      { label: 'Boîte de vitesse', name: 'type_boite', type: 'select', staticOptions: [
        { value: 'manuelle', label: 'Manuelle' },
        { value: 'automatique', label: 'Automatique' },
        { value: 'semi_automatique', label: 'Semi-automatique' },
      ]},
      { label: 'Date acquisition', name: 'date_acquisition', type: 'date' },
      { label: 'Description', name: 'description', type: 'textarea' },
      { label: 'Photos', name: 'images', type: 'file', multiple: true, accept: 'image/*' },
    ],
    menu: { label: 'Vehicules' },
  },
  clients: {
    title: 'Clients',
    description: 'Carnet de clients particuliers et professionnels, avec historique des achats et locations.',
    endpoint: '/clients',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Ajouter un client',
    fields: ['Nom', 'Telephone', 'Email', 'Type client', 'Classe'],
    columns: [
      { label: 'Nom', key: 'nom' },
      { label: 'Telephone', key: 'telephone' },
      { label: 'Email', key: 'email' },
      { label: 'Type client', key: 'type_client' },
      { label: 'Classe', key: 'classe' },
    ],
    formFields: [
      { label: 'Nom *', name: 'nom', required: true },
      { label: 'Prénom', name: 'prenom' },
      { label: 'Date de naissance', name: 'date_naissance', type: 'date' },
      { label: 'Téléphone', name: 'telephone' },
      { label: 'Email', name: 'email', type: 'email' },
      { label: 'Adresse', name: 'adresse', type: 'textarea' },
      { label: "Type de pièce d'identité", name: 'piece_identite', type: 'select', staticOptions: [
        { value: 'CNI', label: "Carte nationale d'identité" },
        { value: 'passeport', label: 'Passeport' },
        { value: 'permis', label: 'Permis de conduire' },
        { value: 'titre_sejour', label: 'Titre de séjour' },
      ]},
      { label: "Numéro de pièce", name: 'numero_piece' },
      { label: 'Type de client', name: 'type_client', type: 'select', staticOptions: [
        { value: 'particulier', label: 'Particulier' },
        { value: 'professionnel', label: 'Professionnel / Entreprise' },
      ]},
      { label: 'Raison sociale', name: 'raison_sociale' },
      { label: 'NINEA', name: 'numero_siret' },
      { label: 'Vendeur attribué', name: 'id_vendeur_attribue', type: 'select', optionsEndpoint: '/employes/select?role=commercial', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Employé #${option?.id}` },
    ],
    detailRoute: 'clients',
    menu: { label: 'Clients' },
  },
  fournisseurs: {
    title: 'Fournisseurs',
    description: 'Répertoire des fournisseurs et partenaires ayant approvisionné le parc en véhicules.',
    endpoint: '/fournisseurs',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Ajouter un fournisseur',
    fields: ['Nom', 'Contact', 'Pays origine', 'Vehicules fournis'],
    columns: [
      { label: 'Nom', key: 'nom' },
      { label: 'Telephone', key: 'telephone' },
      { label: 'Email', key: 'email' },
      { label: 'Pays origine', key: 'pays_origine' },
    ],
    formFields: [
      { label: 'Nom', name: 'nom', required: true },
      { label: 'Adresse', name: 'adresse', type: 'textarea' },
      { label: 'Telephone', name: 'telephone' },
      { label: 'Email', name: 'email', type: 'email' },
      { label: 'Lien', name: 'lien' },
      { label: 'Adresse bureau', name: 'adresse_bureau', type: 'textarea' },
      { label: 'Pays origine', name: 'pays_origine' },
      { label: 'Vehicules fournis', name: 'vehicule_fournis', type: 'textarea' },
    ],
    detailRoute: 'fournisseurs',
    menu: { label: 'Fournisseurs' },
  },
  ventes: {
    title: 'Ventes',
    description: 'Initiez et suivez les ventes de véhicules, de la demande à la signature du contrat.',
    endpoint: '/ventes',
    kind: 'workflow',
    status: 'api-ready',
    primaryAction: 'Nouvelle vente',
    fields: ['Reference', 'Client', 'Vehicule', 'Prix final', 'Statut'],
    columns: [
      { label: 'Reference', key: 'reference_vente' },
      { label: 'Client', key: 'client.nom' },
      { label: 'Vehicule', key: 'voiture.marque' },
      { label: 'Prix final', key: 'prix_final', type: 'money' as const },
      { label: 'Statut', key: 'statut', type: 'badge' as const },
    ],
    formFields: [
      { label: 'Date vente', name: 'date_vente', type: 'date', required: true },
      { label: 'Client', name: 'id_client', type: 'select', required: true, optionsEndpoint: '/clients', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Client #${option?.id}` },
      { label: 'Vehicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Vehicule #${option?.id}` },
      { label: 'Prix final', name: 'prix_final', type: 'number', required: true },
      { label: 'Statut', name: 'statut', required: true },
      { label: 'Employe', name: 'id_employe', type: 'select', required: true, optionsEndpoint: '/employes', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Employe #${option?.id}` },
    ],
    menu: { label: 'Nouvelle vente' },
  },
  facturations: {
    title: 'Facturation',
    description: 'Émettez, consultez et exportez toutes les factures liées aux ventes et locations.',
    endpoint: '/facturations',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Creer une facture',
    fields: ['Numero', 'Vente', 'Location', 'Montant HT', 'Montant TTC', 'Statut'],
    columns: [
      { label: 'Numero', key: 'numero_facture' },
      { label: 'Vente', key: 'vente.reference_vente' },
      { label: 'Location', key: 'location.reference_location' },
      { label: 'Montant HT', key: 'montant_ht', type: 'money' as const },
      { label: 'Montant TTC', key: 'montant_ttc', type: 'money' as const },
      { label: 'Statut', key: 'statut', type: 'badge' as const },
    ],
    formFields: [
      { label: 'Vente', name: 'id_vente', type: 'select', required: true, optionsEndpoint: '/ventes', optionFormatter: (option) => option?.reference_vente || `Vente #${option?.id}` },
      { label: 'Date facture', name: 'date_facture', type: 'date', required: true },
      { label: 'Montant', name: 'montant', type: 'number' },
      { label: 'Remise', name: 'remise', type: 'number' },
      { label: 'TVA', name: 'taux_tva', type: 'number', defaultValue: 18 },
      { label: 'Statut', name: 'statut' },
      { label: 'Mode livraison', name: 'mode_livraison' },
      { label: 'Echeance', name: 'date_echeance', type: 'date' },
      { label: 'Observations', name: 'observations', type: 'textarea' },
    ],
    exportRoute: 'facturations',
    exportFilename: (item) => `facture-${item.numero_facture ?? item.id}.pdf`,
    menu: { label: 'Facturation' },
  },
  paiements: {
    title: 'Paiements',
    description: 'Enregistrez les règlements reçus et suivez les soldes restants par facture.',
    endpoint: '/paiements',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Enregistrer un paiement',
    fields: ['Date', 'Mode', 'Montant', 'Reste', 'Facture'],
    columns: [
      { label: 'Date', key: 'date', type: 'date' as const },
      { label: 'Mode', key: 'mode_paiement' },
      { label: 'Montant', key: 'montant', type: 'money' as const },
      { label: 'Reste', key: 'reste', type: 'money' as const },
      { label: 'Facture', key: 'facturation.numero_facture' },
    ],
    formFields: [
      { label: 'Date', name: 'date', type: 'date', required: true },
      { label: 'Mode paiement', name: 'mode_paiement', required: true },
      { label: 'Montant', name: 'montant', type: 'number', required: true },
      { label: 'Facture', name: 'id_facture', type: 'select', required: true, optionsEndpoint: '/facturations', optionFormatter: (option) => option?.numero_facture || `Facture #${option?.id}` },
      { label: 'Vente', name: 'id_vente', type: 'select', hidden: true, optionsEndpoint: '/ventes', optionFormatter: (option) => option?.reference_vente || `Vente #${option?.id}` },
      { label: 'Client', name: 'id_client', type: 'select', hidden: true, optionsEndpoint: '/clients', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Client #${option?.id}` },
    ],
    transformOnSubmit: (data) => {
      const next = { ...data };
      delete next.id_vente;
      delete next.id_client;
      return next;
    },
    exportRoute: 'paiements',
    exportFilename: (item) => `recu-paiement-${item.id}.pdf`,
    menu: { label: 'Paiements' },
  },
  garanties: {
    title: 'Garanties',
    description: 'Couvrez chaque véhicule vendu avec un plan de garantie constructeur ou commercial.',
    endpoint: '/garanties',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Ajouter une garantie',
    fields: ['Vehicule', 'Type', 'Date debut', 'Date fin'],
    columns: [
      { label: 'Vehicule', key: 'voiture.marque' },
      { label: 'Type', key: 'type_garantie' },
      { label: 'Date debut', key: 'date_debut', type: 'date' as const },
      { label: 'Date fin', key: 'date_fin', type: 'date' as const },
    ],
    formFields: [
      { label: 'Vehicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Vehicule #${option?.id}` },
      { label: 'Type de garantie', name: 'type_garantie', type: 'select', required: true, staticOptions: [
        { value: 'constructeur', label: 'Garantie constructeur' },
        { value: 'commerciale', label: 'Garantie commerciale' },
        { value: 'extension', label: 'Extension de garantie' },
        { value: 'pieces_detachees', label: 'Pièces détachées' },
        { value: 'main_oeuvre', label: "Main d'œuvre" },
        { value: 'satisfaction', label: 'Satisfaction client' },
      ]},
      { label: 'Durée (mois)', name: 'duree_garantie', type: 'number' },
      { label: 'Date début', name: 'date_debut', type: 'date', required: true },
      { label: 'Date fin', name: 'date_fin', type: 'date', required: true },
    ],
    exportRoute: 'garanties',
    exportFilename: (item) => `garantie-${item.id}.pdf`,
    menu: { label: 'Garanties' },
  },
  documents: {
    title: 'Documents',
    description: 'Archivez et retrouvez tous les documents administratifs liés aux véhicules et clients.',
    endpoint: '/documents',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Ajouter un document',
    fields: ['Type', 'Numero', 'Client', 'Vente', 'Expiration'],
    columns: [
      { label: 'Type', key: 'type_document' },
      { label: 'Numero', key: 'numero_document' },
      { label: 'Client', key: 'client.nom' },
      { label: 'Vente', key: 'vente.reference_vente' },
      { label: 'Expiration', key: 'date_expiration', type: 'date' as const },
    ],
    formFields: [
      { label: 'Type document', name: 'type_document', required: true },
      { label: 'Numero document', name: 'numero_document' },
      { label: 'Date document', name: 'date_document', type: 'date' },
      { label: 'Date production', name: 'date_production', type: 'date' },
      { label: 'Client', name: 'id_client', type: 'select', optionsEndpoint: '/clients', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Client #${option?.id}` },
      { label: 'Vente', name: 'id_vente', type: 'select', optionsEndpoint: '/ventes', optionFormatter: (option) => option?.reference_vente || `Vente #${option?.id}` },
      { label: 'Vehicule', name: 'id_voiture', type: 'select', optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Vehicule #${option?.id}` },
      { label: 'Employe', name: 'id_employe', type: 'select', optionsEndpoint: '/employes', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Employe #${option?.id}` },
      { label: 'Expiration', name: 'date_expiration', type: 'date' },
      { label: 'Chemin fichier', name: 'chemin_fichier' },
    ],
    menu: { label: 'Documents' },
  },
  sav: {
    title: 'SAV',
    description: 'Traitez les réclamations et incidents signalés par les clients après livraison ou location.',
    endpoint: '/tickets-sav',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Ouvrir un ticket',
    fields: ['Reference', 'Client', 'Vehicule', 'Priorite', 'Statut'],
    columns: [
      { label: 'Reference', key: 'reference_ticket' },
      { label: 'Client', key: 'client.nom' },
      { label: 'Vehicule', key: 'voiture.marque' },
      { label: 'Priorite', key: 'priorite', type: 'badge' as const },
      { label: 'Statut', key: 'statut', type: 'badge' as const },
    ],
    formFields: [
      { label: 'Client', name: 'id_client', type: 'select', required: true, optionsEndpoint: '/clients', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Client #${option?.id}` },
      { label: 'Vehicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Vehicule #${option?.id}` },
      { label: 'Responsable SAV', name: 'id_responsable', type: 'select', required: true, optionsEndpoint: '/employes/select?role=sav', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') + (option?.poste ? ` (${option.poste})` : '') || `Employé #${option?.id}` },
      { label: 'Garantie liée', name: 'id_garantie', type: 'select', optionsEndpoint: '/garanties', optionFormatter: (option) => option?.type_garantie || `Garantie #${option?.id}` },
      { label: 'Objet', name: 'objet', required: true },
      { label: 'Priorité', name: 'priorite', type: 'select', staticOptions: [
        { value: 'faible', label: 'Faible' },
        { value: 'normale', label: 'Normale' },
        { value: 'haute', label: 'Haute' },
        { value: 'urgente', label: 'Urgente' },
      ]},
      { label: 'Description', name: 'description', type: 'textarea' },
      { label: 'Statut', name: 'statut', type: 'select', staticOptions: [
        { value: 'ouvert', label: 'Ouvert' },
        { value: 'en_cours', label: 'En cours' },
        { value: 'en_attente_pieces', label: 'En attente de pièces' },
        { value: 'resolu', label: 'Résolu' },
        { value: 'ferme', label: 'Fermé' },
      ]},
      { label: 'Date ouverture', name: 'date_ouverture', type: 'date' },
      { label: 'Date résolution', name: 'date_resolution', type: 'date' },
    ],
    detailRoute: 'sav',
    menu: { label: 'SAV' },
  },
  atelier: {
    title: 'Atelier',
    description: 'Planifiez et suivez les ordres de travail confiés aux techniciens de l\'atelier.',
    endpoint: '/ordres-travail',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Nouvel ordre de travail',
    fields: ['Reference OT', 'Vehicule', 'Technicien', 'Priorite', 'Statut'],
    columns: [
      { label: 'Reference OT', key: 'reference_ot' },
      { label: 'Vehicule', key: 'voiture.marque' },
      { label: 'Technicien', key: 'technicien.nom' },
      { label: 'Priorite', key: 'priorite', type: 'badge' as const },
      { label: 'Statut', key: 'statut', type: 'badge' as const },
    ],
    formFields: [
      { label: 'Vehicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Vehicule #${option?.id}` },
      { label: 'Ticket SAV lié', name: 'id_ticket_sav', type: 'select', optionsEndpoint: '/tickets-sav', optionFormatter: (option) => option?.reference_ticket || `Ticket #${option?.id}` },
      { label: 'Technicien', name: 'id_technicien', type: 'select', optionsEndpoint: '/employes/select?role=atelier', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') + (option?.poste ? ` (${option.poste})` : '') || `Employé #${option?.id}` },
      { label: 'Priorité', name: 'priorite', type: 'select', staticOptions: [
        { value: 'faible', label: 'Faible' },
        { value: 'normale', label: 'Normale' },
        { value: 'haute', label: 'Haute' },
        { value: 'urgente', label: 'Urgente' },
      ]},
      { label: 'Deadline', name: 'deadline', type: 'date' },
      { label: 'Description', name: 'description', type: 'textarea', required: true },
    ],
    detailRoute: 'atelier',
    menu: { label: 'Atelier' },
  },
  locations: {
    title: 'Locations',
    description: 'Gérez les contrats de location, du départ à la restitution du véhicule.',
    endpoint: '/locations',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Nouvelle location',
    fields: ['Reference', 'Client', 'Vehicule', 'Responsable', 'Debut', 'Fin', 'Statut'],
    columns: [
      { label: 'Reference', key: 'reference_location' },
      { label: 'Client', key: 'client.nom' },
      { label: 'Vehicule', key: 'voiture.marque' },
      { label: 'Responsable', key: 'agent.nom' },
      { label: 'Debut', key: 'date_debut', type: 'date' as const },
      { label: 'Fin', key: 'date_fin', type: 'date' as const },
      { label: 'Statut', key: 'statut', type: 'badge' as const },
    ],
    formFields: [
      { label: 'Client', name: 'id_client', type: 'select', required: true, optionsEndpoint: '/clients', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Client #${option?.id}` },
      { label: 'Vehicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Vehicule #${option?.id}` },
      { label: 'Date debut', name: 'date_debut', type: 'date', required: true },
      { label: 'Date fin', name: 'date_fin', type: 'date', required: true },
      { label: 'Agent responsable', name: 'id_agent', type: 'select', optionsEndpoint: '/employes/select?poste=location', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Employé #${option?.id}` },
      { label: 'Tarif journalier (XOF)', name: 'tarif_journalier', type: 'number', required: true },
      { label: 'Caution (XOF)', name: 'caution', type: 'number' },
      { label: 'TVA (%)', name: 'taux_tva', type: 'number' },
      { label: "Date d'échéance paiement", name: 'date_echeance', type: 'date' },
      { label: 'Statut', name: 'statut', type: 'select', staticOptions: [
        { value: 'planifiee', label: 'Planifiée' },
        { value: 'en_cours', label: 'En cours' },
        { value: 'terminee', label: 'Terminée' },
        { value: 'annulee', label: 'Annulée' },
      ]},
      { label: 'Observations', name: 'observations', type: 'textarea' },
    ],
    detailRoute: 'locations',
    exportRoute: 'locations',
    exportFilename: (item) => `contrat-${item.reference_location ?? item.id}.pdf`,
    menu: { label: 'Locations' },
  },
  stock: {
    title: 'Stock',
    description: 'Suivez les niveaux de pièces détachées et recevez des alertes en cas de stock critique.',
    endpoint: '/pieces-stock',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Ajouter une piece',
    fields: ['Reference', 'Designation', 'Prix unitaire', 'Quantite', 'Seuil'],
    columns: [
      { label: 'Photo', key: 'image', type: 'image' as const },
      { label: 'Reference', key: 'reference' },
      { label: 'Designation', key: 'designation' },
      { label: 'Prix unitaire', key: 'prix_unitaire', type: 'money' as const },
      { label: 'Quantite', key: 'quantite_stock', type: 'number' as const },
      { label: 'Seuil', key: 'seuil_alerte', type: 'number' as const },
    ],
    formFields: [
      { label: 'Reference', name: 'reference', required: true },
      { label: 'Designation', name: 'designation', required: true },
      { label: 'Description', name: 'description', type: 'textarea' },
      { label: 'Photo', name: 'image', type: 'file', accept: 'image/*' },
      { label: 'Prix unitaire (XOF)', name: 'prix_unitaire', type: 'number', required: true },
      { label: 'Quantite en stock', name: 'quantite_stock', type: 'number' },
      { label: 'Seuil alerte', name: 'seuil_alerte', type: 'number' },
      { label: 'Statut', name: 'statut' },
    ],
    menu: { label: 'Stock' },
  },
  employes: {
    title: 'Employés',
    description: 'Fiches du personnel, postes, contrats et droits d\'accès des collaborateurs.',
    endpoint: '/employes',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Ajouter un employé',
    fields: ['Nom', 'Poste', 'Téléphone', 'Email', 'Statut'],
    columns: [
      { label: 'Nom',       key: 'nom' },
      { label: 'Prénom',    key: 'prenom' },
      { label: 'Poste',     key: 'poste' },
      { label: 'Téléphone', key: 'telephone' },
      { label: 'Statut',    key: 'statut', type: 'badge' as const },
    ],
    formFields: [
      { label: 'Nom',             name: 'nom',          required: true },
      { label: 'Prénom',          name: 'prenom' },
      { label: 'Poste',           name: 'poste',         required: true },
      { label: 'Téléphone',       name: 'telephone' },
      { label: 'Email',           name: 'email',         type: 'email' },
      { label: 'Adresse',         name: 'adresse',       type: 'textarea' },
      { label: 'Date embauche',   name: 'date_embauche', type: 'date' },
      { label: 'Salaire (XOF)',   name: 'salaire',       type: 'number' },
      { label: 'Type de contrat', name: 'contrat', type: 'select', staticOptions: [
        { value: 'CDI', label: 'CDI' },
        { value: 'CDD', label: 'CDD' },
        { value: 'stage', label: 'Stage' },
        { value: 'freelance', label: 'Freelance / Prestataire' },
      ]},
      { label: 'Statut', name: 'statut', type: 'select', staticOptions: [
        { value: 'actif', label: 'Actif' },
        { value: 'inactif', label: 'Inactif' },
        { value: 'conge', label: 'En congé' },
      ]},
    ],
    menu: { label: 'Employés' },
  },
  assurances: {
    title: 'Assurances',
    description: 'Polices d\'assurance actives par véhicule, suivi des échéances et renouvellements.',
    endpoint: '/assurances',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Nouvelle assurance',
    fields: ['Véhicule', 'Compagnie', 'Type', 'Début', 'Fin', 'Statut'],
    columns: [
      { label: 'Véhicule', key: 'voiture.marque' },
      { label: 'Compagnie', key: 'compagnie' },
      { label: 'Type', key: 'type_assurance' },
      { label: 'Début', key: 'date_debut', type: 'date' as const },
      { label: 'Fin', key: 'date_fin', type: 'date' as const },
      { label: 'Statut', key: 'statut', type: 'badge' as const },
    ],
    formFields: [
      { label: 'Véhicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Véhicule #${option?.id}` },
      { label: 'Gestionnaire', name: 'id_gestionnaire', type: 'select', optionsEndpoint: '/employes/select?role=assurance', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Employé #${option?.id}` },
      { label: 'Compagnie', name: 'compagnie', required: true },
      { label: 'Numéro de police', name: 'numero_police' },
      { label: 'Type assurance', name: 'type_assurance', type: 'select', staticOptions: [
        { value: 'tous_risques', label: 'Tous risques' },
        { value: 'tiers', label: 'Tiers simple' },
        { value: 'tiers_etendu', label: 'Tiers étendu' },
        { value: 'vol_incendie', label: 'Vol & incendie' },
        { value: 'bris_glace', label: 'Bris de glace' },
      ]},
      { label: 'Date début', name: 'date_debut', type: 'date', required: true },
      { label: 'Date fin', name: 'date_fin', type: 'date', required: true },
      { label: 'Montant prime (XOF)', name: 'montant_prime', type: 'number' },
      { label: 'Statut', name: 'statut', type: 'select', staticOptions: [
        { value: 'active', label: 'Active' },
        { value: 'expiree', label: 'Expirée' },
        { value: 'suspendue', label: 'Suspendue' },
        { value: 'resiliee', label: 'Résiliée' },
      ]},
      { label: 'Notes', name: 'notes', type: 'textarea' },
    ],
    exportRoute: 'assurances',
    exportFilename: (item) => `assurance-${item.id}.pdf`,
    menu: { label: 'Assurances' },
  },
  carburant: {
    title: 'Carburant',
    description: 'Historique des pleins, consommations et coûts carburant ventilés par véhicule.',
    endpoint: '/carburants',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Enregistrer un plein',
    fields: ['Véhicule', 'Date', 'Km', 'Litres', 'Montant', 'Type'],
    columns: [
      { label: 'Véhicule', key: 'voiture.marque' },
      { label: 'Date', key: 'date_plein', type: 'date' as const },
      { label: 'Km', key: 'kilometrage_au_plein', type: 'km' as const },
      { label: 'Litres', key: 'quantite_litres', type: 'number' as const },
      { label: 'Montant (XOF)', key: 'montant_total', type: 'money' as const },
      { label: 'Type', key: 'type_carburant' },
    ],
    formFields: [
      { label: 'Véhicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Véhicule #${option?.id}` },
      { label: 'Date du plein', name: 'date_plein', type: 'date', required: true },
      { label: 'Kilométrage au plein', name: 'kilometrage_au_plein', type: 'number' },
      { label: 'Quantité (litres)', name: 'quantite_litres', type: 'number' },
      { label: 'Prix par litre', name: 'prix_par_litre', type: 'number' },
      { label: 'Montant total (XOF)', name: 'montant_total', type: 'number', required: true },
      { label: 'Type carburant', name: 'type_carburant', type: 'select', staticOptions: [
        { value: 'essence', label: 'Essence' },
        { value: 'diesel', label: 'Diesel' },
        { value: 'hybride', label: 'Hybride' },
        { value: 'electrique', label: 'Électrique' },
        { value: 'gpl', label: 'GPL' },
      ]},
      { label: 'Station', name: 'station' },
      { label: 'Notes', name: 'notes', type: 'textarea' },
    ],
    menu: { label: 'Carburant' },
  },
  controles_techniques: {
    title: 'Contrôles Techniques',
    description: 'Plannings de contrôles obligatoires, résultats et dates d\'expiration par véhicule.',
    endpoint: '/controles-techniques',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Ajouter un contrôle',
    fields: ['Véhicule', 'Type', 'Date contrôle', 'Expiration', 'Résultat'],
    columns: [
      { label: 'Véhicule', key: 'voiture.marque' },
      { label: 'Type', key: 'type_controle' },
      { label: 'Date contrôle', key: 'date_controle', type: 'date' as const },
      { label: 'Expiration', key: 'date_expiration', type: 'date' as const },
      { label: 'Résultat', key: 'resultat', type: 'badge' as const },
    ],
    formFields: [
      { label: 'Véhicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Véhicule #${option?.id}` },
      { label: 'Type de contrôle', name: 'type_controle', type: 'select', staticOptions: [
        { value: 'periodique', label: 'Périodique' },
        { value: 'mines', label: 'Mines (immatriculation)' },
        { value: 'antipollution', label: 'Antipollution' },
        { value: 'vignette', label: 'Vignette' },
      ]},
      { label: 'Date du contrôle', name: 'date_controle', type: 'date', required: true },
      { label: "Date d'expiration", name: 'date_expiration', type: 'date' },
      { label: 'Résultat', name: 'resultat', type: 'select', staticOptions: [
        { value: 'favorable', label: 'Favorable' },
        { value: 'avec_reserves', label: 'Favorable avec réserves' },
        { value: 'defavorable', label: 'Défavorable' },
      ]},
      { label: 'Organisme', name: 'organisme' },
      { label: 'Coût (XOF)', name: 'cout', type: 'number' },
      { label: 'Observations', name: 'observations', type: 'textarea' },
    ],
    menu: { label: 'Contrôles Tech.' },
  },
  sinistres: {
    title: 'Sinistres',
    description: 'Déclarations de sinistres, suivi des dossiers et remboursements auprès des assureurs.',
    endpoint: '/sinistres',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Déclarer un sinistre',
    fields: ['Véhicule', 'Date', 'Type', 'Statut', 'Montant'],
    columns: [
      { label: 'Véhicule', key: 'voiture.marque' },
      { label: 'Date', key: 'date_sinistre', type: 'date' as const },
      { label: 'Type', key: 'type_sinistre' },
      { label: 'Statut', key: 'statut', type: 'badge' as const },
      { label: 'Dommages (XOF)', key: 'montant_dommages', type: 'money' as const },
    ],
    formFields: [
      { label: 'Véhicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Véhicule #${option?.id}` },
      { label: 'Client impliqué', name: 'id_client', type: 'select', optionsEndpoint: '/clients', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Client #${option?.id}` },
      { label: 'Assurance', name: 'id_assurance', type: 'select', optionsEndpoint: '/assurances', optionFormatter: (option) => option?.compagnie || `Assurance #${option?.id}` },
      { label: 'Gestionnaire sinistre', name: 'id_gestionnaire', type: 'select', optionsEndpoint: '/employes/select?role=assurance', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') || `Employé #${option?.id}` },
      { label: 'Date du sinistre', name: 'date_sinistre', type: 'date', required: true },
      { label: 'Type de sinistre', name: 'type_sinistre', type: 'select', staticOptions: [
        { value: 'accident', label: 'Accident' },
        { value: 'vol', label: 'Vol' },
        { value: 'incendie', label: 'Incendie' },
        { value: 'vandalisme', label: 'Vandalisme' },
        { value: 'bris_glace', label: 'Bris de glace' },
        { value: 'catastrophe_naturelle', label: 'Catastrophe naturelle' },
        { value: 'autre', label: 'Autre' },
      ]},
      { label: 'Description', name: 'description', type: 'textarea', required: true },
      { label: 'Montant dommages (XOF)', name: 'montant_dommages', type: 'number' },
      { label: 'Numéro de déclaration', name: 'numero_declaration' },
      { label: 'Statut', name: 'statut', type: 'select', staticOptions: [
        { value: 'declare', label: 'Déclaré' },
        { value: 'en_cours', label: 'En cours d\'instruction' },
        { value: 'indemnise', label: 'Indemnisé' },
        { value: 'rejete', label: 'Rejeté' },
        { value: 'clos', label: 'Clos' },
      ]},
      { label: 'Notes', name: 'notes', type: 'textarea' },
    ],
    exportRoute: 'sinistres',
    exportFilename: (item) => `sinistre-${item.id}.pdf`,
    menu: { label: 'Sinistres' },
  },
  entretiens: {
    title: 'Entretiens',
    description: 'Planification et suivi des opérations d\'entretien préventif et curatif de la flotte.',
    endpoint: '/entretiens',
    kind: 'crud',
    status: 'api-ready',
    primaryAction: 'Planifier un entretien',
    fields: ['Véhicule', 'Type', 'Date prévue', 'Statut', 'Coût'],
    columns: [
      { label: 'Véhicule', key: 'voiture.marque' },
      { label: 'Type', key: 'type_entretien' },
      { label: 'Date prévue', key: 'date_prevue', type: 'date' as const },
      { label: 'Statut', key: 'statut', type: 'badge' as const },
      { label: 'Coût (XOF)', key: 'cout', type: 'money' as const },
    ],
    formFields: [
      { label: 'Véhicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionFormatter: (option) => [option?.marque, option?.modele].filter(Boolean).join(' ') || `Véhicule #${option?.id}` },
      { label: 'Technicien', name: 'id_technicien', type: 'select', optionsEndpoint: '/employes/select?role=atelier', optionFormatter: (option) => [option?.nom, option?.prenom].filter(Boolean).join(' ') + (option?.poste ? ` (${option.poste})` : '') || `Employé #${option?.id}` },
      { label: "Type d'entretien", name: 'type_entretien', type: 'select', required: true, staticOptions: [
        { value: 'vidange', label: 'Vidange & filtres' },
        { value: 'revision', label: 'Révision générale' },
        { value: 'freins', label: 'Freins' },
        { value: 'pneus', label: 'Pneus / roues' },
        { value: 'courroie', label: 'Courroie de distribution' },
        { value: 'climatisation', label: 'Climatisation' },
        { value: 'batterie', label: 'Batterie' },
        { value: 'controle_technique', label: 'Contrôle technique' },
        { value: 'carrosserie', label: 'Carrosserie' },
        { value: 'autre', label: 'Autre' },
      ]},
      { label: 'Date prévue', name: 'date_prevue', type: 'date' },
      { label: 'Date réalisé', name: 'date_realise', type: 'date' },
      { label: 'Km prévu', name: 'kilometrage_prevu', type: 'number' },
      { label: 'Km réalisé', name: 'kilometrage_realise', type: 'number' },
      { label: 'Coût (XOF)', name: 'cout', type: 'number' },
      { label: 'Statut', name: 'statut', type: 'select', staticOptions: [
        { value: 'planifie', label: 'Planifié' },
        { value: 'en_cours', label: 'En cours' },
        { value: 'effectue', label: 'Effectué' },
        { value: 'annule', label: 'Annulé' },
      ]},
      { label: 'Notes', name: 'notes', type: 'textarea' },
    ],
    exportRoute: 'entretiens',
    exportFilename: (item) => `entretien-${item.id}.pdf`,
    menu: { label: 'Entretiens' },
  },
  reporting: {
    title: 'Reporting',
    description: 'Tableaux de bord analytiques, indicateurs clés et exports pour le pilotage de l\'activité.',
    endpoint: '/reporting',
    kind: 'analytics',
    status: 'api-ready',
    primaryAction: 'Exporter les rapports',
    fields: ['CA mensuel', 'Classement vendeurs', 'Stock critique', 'Paiements attente'],
    menu: { label: 'Reporting' },
  },
  profile: {
    title: 'Profil',
    description: 'Vos informations personnelles, mot de passe et préférences de compte.',
    kind: 'settings',
    status: 'api-ready',
    primaryAction: 'Mettre a jour le profil',
    fields: ['Nom', 'Email', 'Role'],
    menu: { label: 'Profil' },
  },
  settings: {
    title: 'Parametres',
    description: 'Personnalisez l\'interface, la langue et les paramètres généraux de l\'application.',
    kind: 'settings',
    status: 'api-ready',
    primaryAction: 'Enregistrer les parametres',
    fields: ['Theme', 'Langue', 'Mot de passe'],
    menu: { label: 'Parametres' },
    hideFromDynamicMenu: true,
  },
};
