export type ModuleStatus = 'api-ready' | 'api-needed' | 'frontend-draft';

export interface ModuleDefinition {
  title: string;
  description: string;
  endpoint?: string;
  status: ModuleStatus;
  primaryAction: string;
  fields: string[];
  columns?: Array<{ label: string; key: string }>;
  formFields?: Array<{
    label: string;
    name: string;
    type?: 'text' | 'email' | 'number' | 'date' | 'textarea' | 'select';
    required?: boolean;
    optionsEndpoint?: string;
    optionLabel?: string;
  }>;
}

export const modules: Record<string, ModuleDefinition> = {
  dashboard: {
    title: 'Tableau de bord',
    description: 'KPIs temps reel, alertes metier et pilotage global du parc automobile.',
    status: 'frontend-draft',
    primaryAction: 'Actualiser les KPIs',
    fields: ['Ventes du mois', 'Chiffre affaires', 'Vehicules disponibles', 'Stock critique'],
  },
  voitures: {
    title: 'Vehicules',
    description: 'CRUD vehicules, statuts, categories, origines et galerie photos.',
    endpoint: '/voitures',
    status: 'api-ready',
    primaryAction: 'Ajouter un vehicule',
    fields: ['Marque', 'Modele', 'Annee', 'Prix XOF', 'Statut'],
    columns: [
      { label: 'Marque', key: 'marque' },
      { label: 'Modele', key: 'modele' },
      { label: 'Annee', key: 'annee' },
      { label: 'Prix XOF', key: 'prix' },
      { label: 'Statut', key: 'statut' },
    ],
    formFields: [
      { label: 'Marque', name: 'marque', required: true },
      { label: 'Modele', name: 'modele', required: true },
      { label: 'Annee', name: 'annee', type: 'number' },
      { label: 'Prix XOF', name: 'prix', type: 'number', required: true },
      { label: 'Statut', name: 'statut', required: true },
      { label: 'Fournisseur', name: 'id_fournisseur', type: 'select', optionsEndpoint: '/fournisseurs', optionLabel: 'nom' },
      { label: 'Energie', name: 'energie' },
      { label: 'Description', name: 'description', type: 'textarea' },
    ],
  },
  clients: {
    title: 'Clients',
    description: 'Fiches clients, classification locale et historique achats, locations, SAV.',
    endpoint: '/clients',
    status: 'api-ready',
    primaryAction: 'Ajouter un client',
    fields: ['Nom', 'Telephone', 'Email', 'Type client', 'Classe'],
    columns: [
      { label: 'Nom', key: 'nom' },
      { label: 'Telephone', key: 'telephone' },
      { label: 'Email', key: 'email' },
      { label: 'Type client', key: 'type_client' },
      { label: 'Classe', key: 'classe' },
    ],
    formFields: [
      { label: 'Nom', name: 'nom', required: true },
      { label: 'Prenom', name: 'prenom' },
      { label: 'Telephone', name: 'telephone' },
      { label: 'Email', name: 'email', type: 'email' },
      { label: 'Type client', name: 'type_client' },
      { label: 'Classe', name: 'classe' },
    ],
  },
  fournisseurs: {
    title: 'Fournisseurs',
    description: 'Fournisseurs de vehicules et tracabilite de l approvisionnement.',
    endpoint: '/fournisseurs',
    status: 'api-ready',
    primaryAction: 'Ajouter un fournisseur',
    fields: ['Nom', 'Contact', 'Pays origine', 'Vehicules fournis'],
    columns: [
      { label: 'Nom', key: 'nom' },
      { label: 'Contact', key: 'contact' },
      { label: 'Telephone', key: 'telephone' },
      { label: 'Email', key: 'email' },
      { label: 'Pays origine', key: 'pays_origine' },
    ],
    formFields: [
      { label: 'Nom', name: 'nom', required: true },
      { label: 'Contact', name: 'contact' },
      { label: 'Telephone', name: 'telephone' },
      { label: 'Email', name: 'email', type: 'email' },
      { label: 'Pays origine', name: 'pays_origine' },
      { label: 'Vehicules fournis', name: 'vehicule_fournis', type: 'textarea' },
    ],
  },
  ventes: {
    title: 'Ventes',
    description: 'Workflow de vente avec reference, client, vehicule, prix final et statut.',
    endpoint: '/ventes',
    status: 'api-ready',
    primaryAction: 'Nouvelle vente',
    fields: ['Reference', 'Client', 'Vehicule', 'Prix final', 'Statut'],
    columns: [
      { label: 'Reference', key: 'reference_vente' },
      { label: 'Client', key: 'client.nom' },
      { label: 'Vehicule', key: 'voiture.marque' },
      { label: 'Prix final', key: 'prix_final' },
      { label: 'Statut', key: 'statut' },
    ],
    formFields: [
      { label: 'Date vente', name: 'date_vente', type: 'date', required: true },
      { label: 'Client', name: 'id_client', type: 'select', required: true, optionsEndpoint: '/clients', optionLabel: 'nom' },
      { label: 'Vehicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionLabel: 'marque' },
      { label: 'Prix final', name: 'prix_final', type: 'number', required: true },
      { label: 'Statut', name: 'statut', required: true },
      { label: 'Employe', name: 'id_employe', type: 'select', required: true, optionsEndpoint: '/employes', optionLabel: 'nom' },
    ],
  },
  facturations: {
    title: 'Facturation',
    description: 'Factures, TVA 18%, remises, echeances et exports PDF.',
    endpoint: '/facturations',
    status: 'api-ready',
    primaryAction: 'Creer une facture',
    fields: ['Numero', 'Vente', 'Montant HT', 'Montant TTC', 'Statut'],
    columns: [
      { label: 'Numero', key: 'numero_facture' },
      { label: 'Vente', key: 'vente.reference_vente' },
      { label: 'Montant HT', key: 'montant_ht' },
      { label: 'Montant TTC', key: 'montant_ttc' },
      { label: 'Statut', key: 'statut' },
    ],
    formFields: [
      { label: 'Vente', name: 'id_vente', type: 'select', required: true, optionsEndpoint: '/ventes', optionLabel: 'reference_vente' },
      { label: 'Date facture', name: 'date_facture', type: 'date', required: true },
      { label: 'Montant', name: 'montant', type: 'number' },
      { label: 'Remise', name: 'remise', type: 'number' },
      { label: 'TVA', name: 'taux_tva', type: 'number' },
      { label: 'Statut', name: 'statut' },
      { label: 'Echeance', name: 'date_echeance', type: 'date' },
      { label: 'Observations', name: 'observations', type: 'textarea' },
    ],
  },
  paiements: {
    title: 'Paiements',
    description: 'Reglements, paiements fractionnes, modes locaux et soldes restants.',
    endpoint: '/paiements',
    status: 'api-ready',
    primaryAction: 'Enregistrer un paiement',
    fields: ['Date', 'Mode', 'Montant', 'Reste', 'Facture'],
    columns: [
      { label: 'Date', key: 'date' },
      { label: 'Mode', key: 'mode_paiement' },
      { label: 'Montant', key: 'montant' },
      { label: 'Reste', key: 'reste' },
      { label: 'Facture', key: 'facturation.numero_facture' },
    ],
    formFields: [
      { label: 'Date', name: 'date', type: 'date', required: true },
      { label: 'Mode paiement', name: 'mode_paiement', required: true },
      { label: 'Montant', name: 'montant', type: 'number', required: true },
      { label: 'Facture', name: 'id_facture', type: 'select', optionsEndpoint: '/facturations', optionLabel: 'numero_facture' },
      { label: 'Vente', name: 'id_vente', type: 'select', optionsEndpoint: '/ventes', optionLabel: 'reference_vente' },
      { label: 'Client', name: 'id_client', type: 'select', optionsEndpoint: '/clients', optionLabel: 'nom' },
    ],
  },
  garanties: {
    title: 'Garanties',
    description: 'Garanties par vehicule, duree, type et dates de couverture.',
    endpoint: '/garanties',
    status: 'api-ready',
    primaryAction: 'Ajouter une garantie',
    fields: ['Vehicule', 'Type', 'Date debut', 'Date fin'],
    columns: [
      { label: 'Vehicule', key: 'voiture.marque' },
      { label: 'Type', key: 'type_garantie' },
      { label: 'Date debut', key: 'date_debut' },
      { label: 'Date fin', key: 'date_fin' },
      { label: 'Statut', key: 'statut' },
    ],
  },
  documents: {
    title: 'Documents',
    description: 'Pieces administratives liees aux ventes, clients, vehicules et employes.',
    endpoint: '/documents',
    status: 'api-ready',
    primaryAction: 'Ajouter un document',
    fields: ['Type', 'Numero', 'Client', 'Vente', 'Expiration'],
    columns: [
      { label: 'Type', key: 'type_document' },
      { label: 'Numero', key: 'numero_document' },
      { label: 'Client', key: 'client.nom' },
      { label: 'Vente', key: 'vente.reference_vente' },
      { label: 'Expiration', key: 'date_expiration' },
    ],
    formFields: [
      { label: 'Type document', name: 'type_document', required: true },
      { label: 'Numero document', name: 'numero_document' },
      { label: 'Date document', name: 'date_document', type: 'date' },
      { label: 'Client', name: 'id_client', type: 'select', optionsEndpoint: '/clients', optionLabel: 'nom' },
      { label: 'Vente', name: 'id_vente', type: 'select', optionsEndpoint: '/ventes', optionLabel: 'reference_vente' },
      { label: 'Vehicule', name: 'id_voiture', type: 'select', optionsEndpoint: '/voitures', optionLabel: 'marque' },
      { label: 'Employe', name: 'id_employe', type: 'select', optionsEndpoint: '/employes', optionLabel: 'nom' },
      { label: 'Expiration', name: 'date_expiration', type: 'date' },
    ],
  },
  sav: {
    title: 'SAV',
    description: 'Tickets de reclamation, priorites, responsables et interventions.',
    endpoint: '/tickets-sav',
    status: 'api-ready',
    primaryAction: 'Ouvrir un ticket',
    fields: ['Reference', 'Client', 'Vehicule', 'Priorite', 'Statut'],
    columns: [
      { label: 'Reference', key: 'reference_ticket' },
      { label: 'Client', key: 'client.nom' },
      { label: 'Vehicule', key: 'voiture.marque' },
      { label: 'Priorite', key: 'priorite' },
      { label: 'Statut', key: 'statut' },
    ],
    formFields: [
      { label: 'Client', name: 'id_client', type: 'select', required: true, optionsEndpoint: '/clients', optionLabel: 'nom' },
      { label: 'Vehicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionLabel: 'marque' },
      { label: 'Responsable', name: 'id_responsable', type: 'select', required: true, optionsEndpoint: '/employes', optionLabel: 'nom' },
      { label: 'Objet', name: 'objet', required: true },
      { label: 'Priorite', name: 'priorite' },
      { label: 'Description', name: 'description', type: 'textarea' },
    ],
  },
  atelier: {
    title: 'Atelier',
    description: 'Ordres de travail, taches, deadlines, temps passe et consommation pieces.',
    endpoint: '/ordres-travail',
    status: 'api-ready',
    primaryAction: 'Nouvel ordre de travail',
    fields: ['Reference OT', 'Vehicule', 'Technicien', 'Priorite', 'Statut'],
    columns: [
      { label: 'Reference OT', key: 'reference_ot' },
      { label: 'Vehicule', key: 'voiture.marque' },
      { label: 'Technicien', key: 'technicien.nom' },
      { label: 'Priorite', key: 'priorite' },
      { label: 'Statut', key: 'statut' },
    ],
    formFields: [
      { label: 'Vehicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionLabel: 'marque' },
      { label: 'Ticket SAV', name: 'id_ticket_sav', type: 'select', optionsEndpoint: '/tickets-sav', optionLabel: 'reference_ticket' },
      { label: 'Technicien', name: 'id_technicien', type: 'select', optionsEndpoint: '/employes', optionLabel: 'nom' },
      { label: 'Priorite', name: 'priorite' },
      { label: 'Deadline', name: 'deadline', type: 'date' },
      { label: 'Description', name: 'description', type: 'textarea', required: true },
    ],
  },
  locations: {
    title: 'Locations',
    description: 'Contrats, reservations, echeances, retours et etats des lieux.',
    endpoint: '/locations',
    status: 'api-ready',
    primaryAction: 'Nouvelle location',
    fields: ['Reference', 'Client', 'Vehicule', 'Debut', 'Fin', 'Statut'],
    columns: [
      { label: 'Reference', key: 'reference_location' },
      { label: 'Client', key: 'client.nom' },
      { label: 'Vehicule', key: 'voiture.marque' },
      { label: 'Debut', key: 'date_debut' },
      { label: 'Fin', key: 'date_fin' },
      { label: 'Statut', key: 'statut' },
    ],
    formFields: [
      { label: 'Client', name: 'id_client', type: 'select', required: true, optionsEndpoint: '/clients', optionLabel: 'nom' },
      { label: 'Vehicule', name: 'id_voiture', type: 'select', required: true, optionsEndpoint: '/voitures', optionLabel: 'marque' },
      { label: 'Date debut', name: 'date_debut', type: 'date', required: true },
      { label: 'Date fin', name: 'date_fin', type: 'date', required: true },
      { label: 'Tarif journalier', name: 'tarif_journalier', type: 'number', required: true },
      { label: 'Caution', name: 'caution', type: 'number' },
      { label: 'Statut', name: 'statut' },
      { label: 'Observations', name: 'observations', type: 'textarea' },
    ],
  },
  stock: {
    title: 'Stock',
    description: 'Pieces de rechange, seuils alerte, mouvements et valorisation.',
    endpoint: '/pieces-stock',
    status: 'api-ready',
    primaryAction: 'Ajouter une piece',
    fields: ['Reference', 'Designation', 'Prix unitaire', 'Quantite', 'Seuil'],
    columns: [
      { label: 'Reference', key: 'reference' },
      { label: 'Designation', key: 'designation' },
      { label: 'Prix unitaire', key: 'prix_unitaire' },
      { label: 'Quantite', key: 'quantite_stock' },
      { label: 'Seuil', key: 'seuil_alerte' },
    ],
    formFields: [
      { label: 'Reference', name: 'reference', required: true },
      { label: 'Designation', name: 'designation', required: true },
      { label: 'Prix unitaire', name: 'prix_unitaire', type: 'number', required: true },
      { label: 'Quantite', name: 'quantite_stock', type: 'number' },
      { label: 'Seuil alerte', name: 'seuil_alerte', type: 'number' },
      { label: 'Statut', name: 'statut' },
    ],
  },
  reporting: {
    title: 'Reporting',
    description: 'Rapports analytiques, CSV, performances commerciales, stock et finance.',
    endpoint: '/reporting',
    status: 'api-ready',
    primaryAction: 'Exporter les rapports',
    fields: ['CA mensuel', 'Classement vendeurs', 'Stock critique', 'Paiements attente'],
  },
};
